export default {
    SPLASH_SCREEN: 'SPLASH', // same as 2
    SIGNUP_SCENE_1: 'SIGNUP1',
    SELECTION_FIELD_SIGNUP: 'SELECTION_FIELD_SIGNUP',
    ENTRY_POINT: 'ENTRY_POINT', // same as 1
    POST_WELCOME_SCREEN: 'POST_WELCOME_SCREEN', // same as 2
    TWO_WAY_SECURITY_SCREEN: 'TWO_WAY_SECURITY_SCREEN', // same as 1
    ACCOUNT_REPORT: 'ACCOUNT_REPORT', // same as 1
    CHANGE_NUMBER_SCENE: 'CHANGE_NUMBER_SCENE',
    CONTACT_PROFILE_TAB: 'CONTACT_PROFILE_TAB',
    REPORT_PROBLEM: 'REPORT_PROBLEM',
    SECURITY_CODE: 'SECURITY_CODE',
    SECURITY_SCREEN: 'SECURITY_SCREEN',
    PROFILE_SETTING: 'PROFILE_SETTING',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    USER_PROFILE_TAB: 'USER_PROFILE_TAB'
}